import type { Metadata } from "next";
import { Michroma, Montserrat, Rubik, Roboto } from "next/font/google"; // Add Rubik
import "../styles/globals.css";
import Footer from "@/components/layouts/footer/Footer";
import { AppProviders } from "@/components/providers/AppProviders";
import PrimaryHeader from "@/components/layouts/header/PrimaryHeader";

// Font imports and config
const michroma = Michroma({
  weight: "400",
  subsets: ["latin"],
  // variable: "--font-michroma",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // include multiple weights as needed
  // variable: "--font-montserrat",
  display: "swap",
});

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // include multiple weights as needed
  // variable: "--font-rubik",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} ${michroma.className} ${montserrat.className} ${roboto?.className} font-sans`}
      >
        <AppProviders>
          <PrimaryHeader />
          {children}
          <Footer />
        </AppProviders>
      </body>
    </html>
  );
}
